{% set name = "area-detector-handlers" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c184c831ebb6214e519b7b9e0676f3736c255db9b57fcedebdd58dfe0a39c5bf

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dask
    - entrypoints
    - h5py
    - pandas
    - tifffile >=2020.8.25

test:
  imports:
    - area_detector_handlers
    - area_detector_handlers.handlers
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest -v --pyargs area_detector_handlers  # [not win]

about:
  home: https://github.com/bluesky/area-detector-handlers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: DataBroker handlers for Area Detector

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - gwbischof
    - conda-forge/event-model
